/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIdRouteImport } from './routes/portal.$id'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardRecoveryRouteImport } from './routes/dashboard.recovery'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as DashboardNewIndexRouteImport } from './routes/dashboard.new.index'
import { Route as DashboardSubmissionIdRouteImport } from './routes/dashboard.submission.$id'
import { Route as DashboardActivityIdRouteImport } from './routes/dashboard.activity.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIdRoute = PortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecoveryRoute = DashboardRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => DashboardRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewIndexRoute = DashboardNewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionIdRoute = DashboardSubmissionIdRouteImport.update({
  id: '/submission/$id',
  path: '/submission/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityIdRoute = DashboardActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/dashboard/recovery': typeof DashboardRecoveryRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/portal/$id': typeof PortalIdRoute
  '/dashboard/activity/$id': typeof DashboardActivityIdRoute
  '/dashboard/submission/$id': typeof DashboardSubmissionIdRoute
  '/dashboard/new/': typeof DashboardNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/dashboard/recovery': typeof DashboardRecoveryRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/portal/$id': typeof PortalIdRoute
  '/dashboard/activity/$id': typeof DashboardActivityIdRoute
  '/dashboard/submission/$id': typeof DashboardSubmissionIdRoute
  '/dashboard/new': typeof DashboardNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/dashboard/recovery': typeof DashboardRecoveryRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/portal/$id': typeof PortalIdRoute
  '/dashboard/activity/$id': typeof DashboardActivityIdRoute
  '/dashboard/submission/$id': typeof DashboardSubmissionIdRoute
  '/dashboard/new/': typeof DashboardNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/accept-invite/$token'
    | '/dashboard/recovery'
    | '/dashboard/team'
    | '/portal/$id'
    | '/dashboard/activity/$id'
    | '/dashboard/submission/$id'
    | '/dashboard/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/accept-invite/$token'
    | '/dashboard/recovery'
    | '/dashboard/team'
    | '/portal/$id'
    | '/dashboard/activity/$id'
    | '/dashboard/submission/$id'
    | '/dashboard/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/accept-invite/$token'
    | '/dashboard/recovery'
    | '/dashboard/team'
    | '/portal/$id'
    | '/dashboard/activity/$id'
    | '/dashboard/submission/$id'
    | '/dashboard/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  PortalIdRoute: typeof PortalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$id': {
      id: '/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof PortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recovery': {
      id: '/dashboard/recovery'
      path: '/recovery'
      fullPath: '/dashboard/recovery'
      preLoaderRoute: typeof DashboardRecoveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new/': {
      id: '/dashboard/new/'
      path: '/new'
      fullPath: '/dashboard/new/'
      preLoaderRoute: typeof DashboardNewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submission/$id': {
      id: '/dashboard/submission/$id'
      path: '/submission/$id'
      fullPath: '/dashboard/submission/$id'
      preLoaderRoute: typeof DashboardSubmissionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity/$id': {
      id: '/dashboard/activity/$id'
      path: '/activity/$id'
      fullPath: '/dashboard/activity/$id'
      preLoaderRoute: typeof DashboardActivityIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardRecoveryRoute: typeof DashboardRecoveryRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardActivityIdRoute: typeof DashboardActivityIdRoute
  DashboardSubmissionIdRoute: typeof DashboardSubmissionIdRoute
  DashboardNewIndexRoute: typeof DashboardNewIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRecoveryRoute: DashboardRecoveryRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardActivityIdRoute: DashboardActivityIdRoute,
  DashboardSubmissionIdRoute: DashboardSubmissionIdRoute,
  DashboardNewIndexRoute: DashboardNewIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  PortalIdRoute: PortalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
